/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseCard: typeof import('./src/components/Card/BaseCard.vue')['default']
    Card: typeof import('./src/components/Card.vue')['default']
    Cards: typeof import('./src/components/Card/Cards.vue')['default']
    CommunityCard: typeof import('./src/components/CommunityCard.vue')['default']
    FastCard: typeof import('./src/components/FastCard.vue')['default']
    FileBasedRoutingCard: typeof import('./src/components/FileBasedRoutingCard.vue')['default']
    FileBaseRouting: typeof import('./src/components/FileBaseRouting.vue')['default']
    FooterBar: typeof import('./src/components/Footer/FooterBar.vue')['default']
    FooterIcon: typeof import('./src/components/Footer/FooterIcon.vue')['default']
    FooterSocialIcons: typeof import('./src/components/Footer/FooterSocialIcons.vue')['default']
    GetStarted: typeof import('./src/components/GetStarted.vue')['default']
    GithubCard: typeof import('./src/components/GithubCard.vue')['default']
    Icon: typeof import('@iconify/vue')['Icon']
    InputComponent: typeof import('./src/components/Input/InputComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SocialMediaCard: typeof import('./src/components/SocialMediaCard.vue')['default']
    ThemeSwitch: typeof import('./src/components/Theme/ThemeSwitch.vue')['default']
    TypeScriptCard: typeof import('./src/components/TypeScriptCard.vue')['default']
    VueWelcome: typeof import('./src/components/VueWelcome.vue')['default']
    WelcomeCard: typeof import('./src/components/Card/WelcomeCard.vue')['default']
  }
}
